// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rpstreams.h"
#include <Rcpp.h>

using namespace Rcpp;

// make_pstream
handle make_pstream(std::string command, SEXP args);
RcppExport SEXP rpstreams_make_pstream(SEXP commandSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    Rcpp::traits::input_parameter< SEXP >::type args(argsSEXP);
    __result = Rcpp::wrap(make_pstream(command, args));
    return __result;
END_RCPP
}
// close_
void close_(handle s);
RcppExport SEXP rpstreams_close_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    close_(s);
    return R_NilValue;
END_RCPP
}
// write_stdin_
void write_stdin_(handle s, std::string v);
RcppExport SEXP rpstreams_write_stdin_(SEXP sSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type v(vSEXP);
    write_stdin_(s, v);
    return R_NilValue;
END_RCPP
}
// read_stdout_
std::string read_stdout_(handle s, double timeout);
RcppExport SEXP rpstreams_read_stdout_(SEXP sSEXP, SEXP timeoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type timeout(timeoutSEXP);
    __result = Rcpp::wrap(read_stdout_(s, timeout));
    return __result;
END_RCPP
}
// read_stderr_
std::string read_stderr_(handle s, double timeout);
RcppExport SEXP rpstreams_read_stderr_(SEXP sSEXP, SEXP timeoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type timeout(timeoutSEXP);
    __result = Rcpp::wrap(read_stderr_(s, timeout));
    return __result;
END_RCPP
}
// is_open_
bool is_open_(handle s);
RcppExport SEXP rpstreams_is_open_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(is_open_(s));
    return __result;
END_RCPP
}
// is_eof_
bool is_eof_(handle s);
RcppExport SEXP rpstreams_is_eof_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(is_eof_(s));
    return __result;
END_RCPP
}
// is_good_
bool is_good_(handle s);
RcppExport SEXP rpstreams_is_good_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(is_good_(s));
    return __result;
END_RCPP
}
// is_bad_
bool is_bad_(handle s);
RcppExport SEXP rpstreams_is_bad_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(is_bad_(s));
    return __result;
END_RCPP
}
// is_fail_
bool is_fail_(handle s);
RcppExport SEXP rpstreams_is_fail_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(is_fail_(s));
    return __result;
END_RCPP
}
// send_eof_
void send_eof_(handle s);
RcppExport SEXP rpstreams_send_eof_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    send_eof_(s);
    return R_NilValue;
END_RCPP
}
// exit_code_
int exit_code_(handle s);
RcppExport SEXP rpstreams_exit_code_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(exit_code_(s));
    return __result;
END_RCPP
}
// errno_
int errno_(handle s);
RcppExport SEXP rpstreams_errno_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(errno_(s));
    return __result;
END_RCPP
}
// has_exited_
bool has_exited_(handle s);
RcppExport SEXP rpstreams_has_exited_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    __result = Rcpp::wrap(has_exited_(s));
    return __result;
END_RCPP
}
// signal_
void signal_(handle s, int signal, bool group);
RcppExport SEXP rpstreams_signal_(SEXP sSEXP, SEXP signalSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< handle >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< bool >::type group(groupSEXP);
    signal_(s, signal, group);
    return R_NilValue;
END_RCPP
}
