# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_pstream <- function(command, args) {
    .Call('rpstreams_make_pstream', PACKAGE = 'rpstreams', command, args)
}

close_ <- function(s) {
    invisible(.Call('rpstreams_close_', PACKAGE = 'rpstreams', s))
}

write_stdin_ <- function(s, v) {
    invisible(.Call('rpstreams_write_stdin_', PACKAGE = 'rpstreams', s, v))
}

read_stdout_ <- function(s) {
    .Call('rpstreams_read_stdout_', PACKAGE = 'rpstreams', s)
}

read_stderr_ <- function(s) {
    .Call('rpstreams_read_stderr_', PACKAGE = 'rpstreams', s)
}

is_open_ <- function(s) {
    .Call('rpstreams_is_open_', PACKAGE = 'rpstreams', s)
}

is_eof_ <- function(s) {
    .Call('rpstreams_is_eof_', PACKAGE = 'rpstreams', s)
}

is_good_ <- function(s) {
    .Call('rpstreams_is_good_', PACKAGE = 'rpstreams', s)
}

is_bad_ <- function(s) {
    .Call('rpstreams_is_bad_', PACKAGE = 'rpstreams', s)
}

is_fail_ <- function(s) {
    .Call('rpstreams_is_fail_', PACKAGE = 'rpstreams', s)
}

send_eof_ <- function(s) {
    invisible(.Call('rpstreams_send_eof_', PACKAGE = 'rpstreams', s))
}

exit_code_ <- function(s) {
    .Call('rpstreams_exit_code_', PACKAGE = 'rpstreams', s)
}

errno_ <- function(s) {
    .Call('rpstreams_errno_', PACKAGE = 'rpstreams', s)
}

has_exited_ <- function(s) {
    .Call('rpstreams_has_exited_', PACKAGE = 'rpstreams', s)
}

signal_ <- function(s, signal, group = FALSE) {
    invisible(.Call('rpstreams_signal_', PACKAGE = 'rpstreams', s, signal, group))
}

